multipart.maxFileSize: -1
server.port: 3333

# bugfix for keycloak spring adapter: https://stackoverflow.com/questions/53318134/unable-to-use-keycloak-in-spring-boot-2-1-due-to-duplicated-bean-registration-ht
spring.main.allow-bean-definition-overriding: true

spring.datasource:
  url: jdbc:mysql://localhost:3306/metaexplorer-editor?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: BizSys_User
  password: reset1This2Password3
  testWhileIdle: true
  validationQuery: SELECT 1

spring.jpa:
  show-sql: false
  # Hibernate ddl auto (create, create-drop, update): with "update" the database
  # schema will be automatically updated accordingly to java entities found in
  # the project
  hibernate:
    ddl-auto: create-drop
    #create-drop
    # Naming strategy
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  generate-ddl: true
  # Allows Hibernate to generate SQL optimized for a particular DBMS
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

keycloak:
  auth-server-url: http://localhost:8081/auth/
  resource: metaExplorer-microClient
  realm: MetaExplorerEditor
  bearer-only: true
  principal-attribute: preferred_username
  cors: true